import { ValueType } from 'realgrid';

export const GridFields1 = [
  { fieldName: 'Goodno', dataType: ValueType.TEXT },
  { fieldName: 'Goodnm', dataType: ValueType.TEXT },
  { fieldName: 'GoodType', dataType: ValueType.TEXT },
  { fieldName: 'GoodTypenm', dataType: ValueType.TEXT },
  { fieldName: 'Wrhnm', dataType: ValueType.TEXT },
  { fieldName: 'Wrhcd', dataType: ValueType.TEXT },
  { fieldName: 'Unitcd', dataType: ValueType.TEXT },
  { fieldName: 'Unitnm', dataType: ValueType.TEXT },
  { fieldName: 'Goodcd', dataType: ValueType.TEXT },
  { fieldName: 'Spec', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods1cd', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods1nm', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods2cd', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods2nm', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods3cd', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods3nm', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods4cd', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods4nm', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsPartcd', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsPartnm', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsPartRemark', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsTypecd', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsTypenm', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsTypeRemark', dataType: ValueType.TEXT },
  { fieldName: 'SeatTypecd', dataType: ValueType.TEXT },
  { fieldName: 'SeatTypenm', dataType: ValueType.TEXT },
  { fieldName: 'RatingTypecd', dataType: ValueType.TEXT },
  { fieldName: 'RatingTypenm', dataType: ValueType.TEXT },
  { fieldName: 'SizeTypecd', dataType: ValueType.TEXT },
  { fieldName: 'SizeTypenm', dataType: ValueType.TEXT },
  { fieldName: 'BdbtStemcd', dataType: ValueType.TEXT },
  { fieldName: 'BdbtStemnm', dataType: ValueType.TEXT },
  { fieldName: 'DiskTypecd', dataType: ValueType.TEXT },
  { fieldName: 'DiskTypenm', dataType: ValueType.TEXT },
  { fieldName: 'Specialcd', dataType: ValueType.TEXT },
  { fieldName: 'Specialnm', dataType: ValueType.TEXT },
  { fieldName: 'Borecd', dataType: ValueType.TEXT },
  { fieldName: 'Borenm', dataType: ValueType.TEXT },
  { fieldName: 'Endcd', dataType: ValueType.TEXT },
  { fieldName: 'Endnm', dataType: ValueType.TEXT },
  { fieldName: 'Bodycd', dataType: ValueType.TEXT },
  { fieldName: 'Bodynm', dataType: ValueType.TEXT },
  { fieldName: 'Trimcd', dataType: ValueType.TEXT },
  { fieldName: 'Trimnm', dataType: ValueType.TEXT },
  { fieldName: 'Operatorcd', dataType: ValueType.TEXT },
  { fieldName: 'Operatornm', dataType: ValueType.TEXT },
  { fieldName: 'PivLength', dataType: ValueType.TEXT },
  { fieldName: 'PivSizecd', dataType: ValueType.TEXT },
  { fieldName: 'PivSizenm', dataType: ValueType.TEXT },
  { fieldName: 'PivSpeccd', dataType: ValueType.TEXT },
  { fieldName: 'PivSpecnm', dataType: ValueType.TEXT },
  { fieldName: 'Jukyocd', dataType: ValueType.TEXT },
  { fieldName: 'Jukyonm', dataType: ValueType.TEXT },
  { fieldName: 'Boxunit', dataType: ValueType.TEXT },
  { fieldName: 'Boxunitnm', dataType: ValueType.TEXT },
  { fieldName: 'Priceunit', dataType: ValueType.TEXT },
  { fieldName: 'Priceunitnm', dataType: ValueType.TEXT },
  { fieldName: 'KgPerM', dataType: ValueType.NUMBER },
  { fieldName: 'Storkyn', dataType: ValueType.TEXT },
  { fieldName: 'Inunit', dataType: ValueType.TEXT },
  { fieldName: 'Inunitnm', dataType: ValueType.TEXT },
  { fieldName: 'Weight', dataType: ValueType.NUMBER },
  { fieldName: 'Stockqty', dataType: ValueType.NUMBER },
  { fieldName: 'ModDate', dataType: ValueType.TEXT },
];

export const GridColumns1 = [
  {
    name: 'Goodno',
    fieldName: 'Goodno',
    type: 'data',
    width: '250',
    header: {
      text: '품목번호',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Goodnm',
    fieldName: 'Goodnm',
    type: 'data',
    width: '220',
    header: {
      text: '품목명',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Spec',
    fieldName: 'Spec',
    type: 'data',
    width: '160',
    header: {
      text: '규격',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'GoodTypenm',
    fieldName: 'GoodTypenm',
    type: 'data',
    width: '60',
    header: {
      text: '재고자산',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SearchGoods1nm',
    fieldName: 'SearchGoods1nm',
    type: 'data',
    width: '100',
    header: {
      text: '대분류',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SearchGoods2nm',
    fieldName: 'SearchGoods2nm',
    type: 'data',
    width: '100',
    header: {
      text: '중분류',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SearchGoods3nm',
    fieldName: 'SearchGoods3nm',
    type: 'data',
    width: '160',
    header: {
      text: '소분류',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SearchGoods4nm',
    fieldName: 'SearchGoods4nm',
    type: 'data',
    width: '160',
    header: {
      text: '강종',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'HalfGoodsPartnm',
    fieldName: 'HalfGoodsPartnm',
    type: 'data',
    width: '250',
    header: {
      text: '반제품Part',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'HalfGoodsTypenm',
    fieldName: 'HalfGoodsTypenm',
    type: 'data',
    width: '250',
    header: {
      text: '반제품Type',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'SeatTypenm',
    fieldName: 'SeatTypenm',
    type: 'data',
    width: '180',
    header: {
      text: 'Seat',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'BdbtStemnm',
    fieldName: 'BdbtStemnm',
    type: 'data',
    width: '180',
    header: {
      text: 'BD-BT&Stem',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'DiskTypenm',
    fieldName: 'DiskTypenm',
    type: 'data',
    width: '180',
    header: {
      text: 'Disk',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Specialnm',
    fieldName: 'Specialnm',
    type: 'data',
    width: '200',
    header: {
      text: 'Special',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'RatingTypenm',
    fieldName: 'RatingTypenm',
    type: 'data',
    width: '160',
    header: {
      text: 'Rating',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Borenm',
    fieldName: 'Borenm',
    type: 'data',
    width: '160',
    header: {
      text: 'Bore',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SizeTypenm',
    fieldName: 'SizeTypenm',
    type: 'data',
    width: '160',
    header: {
      text: 'Size',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Endnm',
    fieldName: 'Endnm',
    type: 'data',
    width: '160',
    header: {
      text: 'End',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Bodynm',
    fieldName: 'Bodynm',
    type: 'data',
    width: '160',
    header: {
      text: 'Body 재질',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Trimnm',
    fieldName: 'Trimnm',
    type: 'data',
    width: '160',
    header: {
      text: 'Trim 재질',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Operatornm',
    fieldName: 'Operatornm',
    type: 'data',
    width: '160',
    header: {
      text: 'Operator',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Pivlength',
    fieldName: 'Pivlength',
    type: 'data',
    width: '160',
    header: {
      text: 'PIV Length',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },

  {
    name: 'PivsizeNm',
    fieldName: 'PivsizeNm',
    type: 'data',
    width: '160',
    header: {
      text: 'PIV Size',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'PivspecNm',
    fieldName: 'PivspecNm',
    type: 'data',
    width: '160',
    header: {
      text: 'PIV Spec',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
];

export const GridFields2 = [
  { fieldName: 'Goodno', dataType: ValueType.TEXT },
  { fieldName: 'Goodnm', dataType: ValueType.TEXT },
  { fieldName: 'GoodType', dataType: ValueType.TEXT },
  { fieldName: 'GoodTypenm', dataType: ValueType.TEXT },
  { fieldName: 'Wrhnm', dataType: ValueType.TEXT },
  { fieldName: 'Wrhcd', dataType: ValueType.TEXT },
  { fieldName: 'Unitcd', dataType: ValueType.TEXT },
  { fieldName: 'Unitnm', dataType: ValueType.TEXT },
  { fieldName: 'Goodcd', dataType: ValueType.TEXT },
  { fieldName: 'Spec', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods1cd', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods1nm', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods2cd', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods2nm', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods3cd', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods3nm', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods4cd', dataType: ValueType.TEXT },
  { fieldName: 'SearchGoods4nm', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsPartcd', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsPartnm', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsPartRemark', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsTypecd', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsTypenm', dataType: ValueType.TEXT },
  { fieldName: 'HalfGoodsTypeRemark', dataType: ValueType.TEXT },
  { fieldName: 'SeatTypecd', dataType: ValueType.TEXT },
  { fieldName: 'SeatTypenm', dataType: ValueType.TEXT },
  { fieldName: 'RatingTypecd', dataType: ValueType.TEXT },
  { fieldName: 'RatingTypenm', dataType: ValueType.TEXT },
  { fieldName: 'SizeTypecd', dataType: ValueType.TEXT },
  { fieldName: 'SizeTypenm', dataType: ValueType.TEXT },
  { fieldName: 'BdbtStemcd', dataType: ValueType.TEXT },
  { fieldName: 'BdbtStemnm', dataType: ValueType.TEXT },
  { fieldName: 'DiskTypecd', dataType: ValueType.TEXT },
  { fieldName: 'DiskTypenm', dataType: ValueType.TEXT },
  { fieldName: 'Specialcd', dataType: ValueType.TEXT },
  { fieldName: 'Specialnm', dataType: ValueType.TEXT },
  { fieldName: 'Borecd', dataType: ValueType.TEXT },
  { fieldName: 'Borenm', dataType: ValueType.TEXT },
  { fieldName: 'Endcd', dataType: ValueType.TEXT },
  { fieldName: 'Endnm', dataType: ValueType.TEXT },
  { fieldName: 'Bodycd', dataType: ValueType.TEXT },
  { fieldName: 'Bodynm', dataType: ValueType.TEXT },
  { fieldName: 'Trimcd', dataType: ValueType.TEXT },
  { fieldName: 'Trimnm', dataType: ValueType.TEXT },
  { fieldName: 'Operatorcd', dataType: ValueType.TEXT },
  { fieldName: 'Operatornm', dataType: ValueType.TEXT },
  { fieldName: 'PivLength', dataType: ValueType.TEXT },
  { fieldName: 'PivSizecd', dataType: ValueType.TEXT },
  { fieldName: 'PivSizenm', dataType: ValueType.TEXT },
  { fieldName: 'PivSpeccd', dataType: ValueType.TEXT },
  { fieldName: 'PivSpecnm', dataType: ValueType.TEXT },
  { fieldName: 'Jukyocd', dataType: ValueType.TEXT },
  { fieldName: 'Jukyonm', dataType: ValueType.TEXT },
  { fieldName: 'Boxunit', dataType: ValueType.TEXT },
  { fieldName: 'Boxunitnm', dataType: ValueType.TEXT },
  { fieldName: 'Priceunit', dataType: ValueType.TEXT },
  { fieldName: 'Priceunitnm', dataType: ValueType.TEXT },
  { fieldName: 'KgPerM', dataType: ValueType.NUMBER },
  { fieldName: 'Storkyn', dataType: ValueType.TEXT },
  { fieldName: 'Inunit', dataType: ValueType.TEXT },
  { fieldName: 'Inunitnm', dataType: ValueType.TEXT },
  { fieldName: 'Weight', dataType: ValueType.NUMBER },
  { fieldName: 'Stockqty', dataType: ValueType.NUMBER },
  { fieldName: 'ModDate', dataType: ValueType.TEXT },
];
////////////////////////////
export const GridColumns2 = [
  {
    name: 'Goodno',
    fieldName: 'Goodno',
    type: 'data',
    width: '250',
    header: {
      text: '품목번호',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Goodnm',
    fieldName: 'Goodnm',
    type: 'data',
    width: '220',
    header: {
      text: '품목명',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Spec',
    fieldName: 'Spec',
    type: 'data',
    width: '160',
    header: {
      text: '규격',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SearchGoods1nm',
    fieldName: 'SearchGoods1nm',
    type: 'data',
    width: '100',
    header: {
      text: '대분류',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SearchGoods2nm',
    fieldName: 'SearchGoods2nm',
    type: 'data',
    width: '100',
    header: {
      text: '중분류',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SearchGoods3nm',
    fieldName: 'SearchGoods3nm',
    type: 'data',
    width: '160',
    header: {
      text: '소분류',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SearchGoods4nm',
    fieldName: 'SearchGoods4nm',
    type: 'data',
    width: '160',
    header: {
      text: '강종',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'HalfGoodsPartnm',
    fieldName: 'HalfGoodsPartnm',
    type: 'data',
    width: '250',
    header: {
      text: '반제품Part',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'HalfGoodsTypenm',
    fieldName: 'HalfGoodsTypenm',
    type: 'data',
    width: '250',
    header: {
      text: '반제품Type',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'SeatTypenm',
    fieldName: 'SeatTypenm',
    type: 'data',
    width: '180',
    header: {
      text: 'Seat',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'BdbtStemnm',
    fieldName: 'BdbtStemnm',
    type: 'data',
    width: '180',
    header: {
      text: 'BD-BT&Stem',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'DiskTypenm',
    fieldName: 'DiskTypenm',
    type: 'data',
    width: '180',
    header: {
      text: 'Disk',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Specialnm',
    fieldName: 'Specialnm',
    type: 'data',
    width: '200',
    header: {
      text: 'Special',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'RatingTypenm',
    fieldName: 'RatingTypenm',
    type: 'data',
    width: '160',
    header: {
      text: 'Rating',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Borenm',
    fieldName: 'Borenm',
    type: 'data',
    width: '160',
    header: {
      text: 'Bore',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'SizeTypenm',
    fieldName: 'SizeTypenm',
    type: 'data',
    width: '160',
    header: {
      text: 'Size',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Endnm',
    fieldName: 'Endnm',
    type: 'data',
    width: '160',
    header: {
      text: 'End',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Bodynm',
    fieldName: 'Bodynm',
    type: 'data',
    width: '160',
    header: {
      text: 'Body 재질',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Trimnm',
    fieldName: 'Trimnm',
    type: 'data',
    width: '160',
    header: {
      text: 'Trim 재질',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Operatornm',
    fieldName: 'Operatornm',
    type: 'data',
    width: '160',
    header: {
      text: 'Operator',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'Pivlength',
    fieldName: 'Pivlength',
    type: 'data',
    width: '160',
    header: {
      text: 'PIV Length',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },

  {
    name: 'PivsizeNm',
    fieldName: 'PivsizeNm',
    type: 'data',
    width: '160',
    header: {
      text: 'PIV Size',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
  {
    name: 'PivspecNm',
    fieldName: 'PivspecNm',
    type: 'data',
    width: '160',
    header: {
      text: 'PIV Spec',
      showTooltip: true,
    },
    styleName: 'left-column',
    editable: false,
  },
];
