import { ValueType } from 'realgrid';

export const GridFields1 = [
  { fieldName: 'Accunit', dataType: ValueType.TEXT },
  { fieldName: 'ApprDocProg', dataType: ValueType.TEXT },
  { fieldName: 'BalDate', dataType: ValueType.DATE, datetimeFormat: 'yyyyMMdd' },
  { fieldName: 'BalNo', dataType: ValueType.TEXT },
  { fieldName: 'ContractNo', dataType: ValueType.TEXT },
  { fieldName: 'CustCd', dataType: ValueType.TEXT },
  { fieldName: 'CustCdNm', dataType: ValueType.TEXT },
  { fieldName: 'delvqty', dataType: ValueType.NUMBER },
  { fieldName: 'DeptCd', dataType: ValueType.TEXT },
  { fieldName: 'DeptCDNm', dataType: ValueType.TEXT },
  { fieldName: 'DocStatus', dataType: ValueType.TEXT },
  { fieldName: 'ExportYn', dataType: ValueType.TEXT },
  { fieldName: 'FileNo', dataType: ValueType.TEXT },
  { fieldName: 'OrderProgressYN', dataType: ValueType.TEXT },
  { fieldName: 'orderqty', dataType: ValueType.NUMBER },
  { fieldName: 'Pno', dataType: ValueType.TEXT },
  { fieldName: 'PnoNm', dataType: ValueType.TEXT },
  { fieldName: 'Remark', dataType: ValueType.TEXT },
  { fieldName: 'TotalAmt', dataType: ValueType.NUMBER },
  { fieldName: 'ToTalVat', dataType: ValueType.NUMBER },
  { fieldName: 'TotalWeight', dataType: ValueType.NUMBER },
  { fieldName: 'TotalOkAmt', dataType: ValueType.NUMBER },
  { fieldName: 'TruncNm', dataType: ValueType.TEXT },
  { fieldName: 'URGENCY', dataType: ValueType.TEXT },
  { fieldName: 'URGENCYNM', dataType: ValueType.TEXT },
  { fieldName: 'Vatcd', dataType: ValueType.TEXT },
  { fieldName: 'VatNm', dataType: ValueType.TEXT },
];

export const GridColumns1 = [
  {
    name: 'ApprDocProg',
    fieldName: 'ApprDocProg',
    width: 54,
    styleName: 'center-column',
    header: {
      text: '결재상태',
    },
  },
  {
    name: 'BalDate',
    fieldName: 'BalDate',
    width: 75,
    styleName: 'center-column',
    header: {
      text: '발주일',
    },

    datetimeFormat: 'yyyy-MM-dd',
  },
  {
    name: 'BalNo',
    fieldName: 'BalNo',
    width: 100,
    styleName: 'center-column',
    header: {
      text: '발주번호',
    },
    datetimeFormat: 'yyyy-MM-dd',
  },

  {
    name: 'CustCdNm',
    fieldName: 'CustCdNm',
    width: 135,
    styleName: 'left-column',
    header: {
      text: '거래처명',
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'OrderProgressYN',
    fieldName: 'OrderProgressYN',
    width: 54,
    styleName: 'center-column',
    header: {
      text: '마감상태',
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
];

export const GridFields2 = [
  { fieldName: 'AcceptPrice', dataType: ValueType.TEXT },
  { fieldName: 'AcceptQty', dataType: ValueType.TEXT },
  { fieldName: 'Accunit', dataType: ValueType.TEXT },
  { fieldName: 'Amount', dataType: ValueType.NUMBER },
  { fieldName: 'BalNo', dataType: ValueType.TEXT },
  { fieldName: 'BalQty', dataType: ValueType.NUMBER },
  { fieldName: 'BalSeq', dataType: ValueType.TEXT },
  { fieldName: 'Clstype', dataType: ValueType.TEXT },
  { fieldName: 'color', dataType: ValueType.TEXT },
  { fieldName: 'CreDate', dataType: ValueType.TEXT },
  { fieldName: 'CrePno', dataType: ValueType.TEXT },
  { fieldName: 'DelvdateA', dataType: ValueType.TEXT },
  { fieldName: 'ExportYn', dataType: ValueType.TEXT },
  { fieldName: 'GoodCd', dataType: ValueType.TEXT },
  { fieldName: 'GoodCdNm', dataType: ValueType.TEXT },
  { fieldName: 'Goodenm', dataType: ValueType.TEXT },
  { fieldName: 'GoodNo', dataType: ValueType.TEXT },
  { fieldName: 'Goodtype', dataType: ValueType.TEXT },
  { fieldName: 'InCnt', dataType: ValueType.NUMBER },
  { fieldName: 'InQty', dataType: ValueType.NUMBER },
  { fieldName: 'Kgperm', dataType: ValueType.NUMBER },
  { fieldName: 'MarkCdNm', dataType: ValueType.TEXT },
  { fieldName: 'ModDate', dataType: ValueType.TEXT },
  { fieldName: 'ModPno', dataType: ValueType.TEXT },
  { fieldName: 'NapDate', dataType: ValueType.TEXT },
  { fieldName: 'NapQty', dataType: ValueType.NUMBER },
  { fieldName: 'No', dataType: ValueType.TEXT },
  { fieldName: 'Okamt', dataType: ValueType.NUMBER },
  { fieldName: 'Price', dataType: ValueType.NUMBER },
  { fieldName: 'Priceunit', dataType: ValueType.TEXT },
  { fieldName: 'ProgType', dataType: ValueType.TEXT },
  { fieldName: 'Qty', dataType: ValueType.NUMBER },
  { fieldName: 'Remark', dataType: ValueType.TEXT },
  { fieldName: 'Spec', dataType: ValueType.TEXT },
  { fieldName: 'StockQty', dataType: ValueType.NUMBER },
  { fieldName: 'Stockunit', dataType: ValueType.TEXT },
  { fieldName: 'StockUnitCd', dataType: ValueType.TEXT },
  { fieldName: 'Stockunitnm', dataType: ValueType.TEXT },
  { fieldName: 'Su', dataType: ValueType.NUMBER },
  { fieldName: 'Suunitnm', dataType: ValueType.TEXT },
  { fieldName: 'Tax', dataType: ValueType.NUMBER },
  { fieldName: 'UnitCd', dataType: ValueType.TEXT },
  { fieldName: 'UnitCdNm', dataType: ValueType.TEXT },
  { fieldName: 'Weight', dataType: ValueType.NUMBER },
  { fieldName: 'Weightunitnm', dataType: ValueType.TEXT },
  { fieldName: 'WonAmt', dataType: ValueType.NUMBER },
];

export const GridColumns2 = [
  {
    name: 'NO',
    fieldName: 'NO',
    width: 40,
    styleName: 'center-column',
    editable: false,
    header: {
      text: 'NO',
    },
  },
  {
    name: 'GoodNo',
    fieldName: 'GoodNo',
    width: 150,
    styleName: 'left-column',
    editable: true,
    header: {
      text: '품번',
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    editor: {
      textCase: 'upper',
    },
  },
  {
    name: 'Spec',
    fieldName: 'Spec',
    width: 200,
    styleName: 'left-column',
    editable: true,
    editor: {
      maxLength: 25,
    },
    header: {
      text: '규격',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'GoodCdNm',
    fieldName: 'GoodCdNm',
    width: 150,
    // button: 'action',
    // editable: false,
    styleName: 'left-column',
    editable: true,
    header: {
      text: '품명',
      showTooltip: true,
    },
  },
  {
    name: 'BalQty',
    fieldName: 'BalQty',
    width: 60,
    styleName: 'right-column',
    editable: true,
    header: {
      text: '발주량',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0.##',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0.##',
    },
    numberFormat: '#,##0.##',
  },
  {
    name: 'UnitCdNm',
    fieldName: 'UnitCdNm',
    width: 50,
    styleName: 'center-column rg-disable-cell',
    editable: false,
    header: {
      text: '단위',
      showTooltip: true,
    },
  },
  {
    name: 'Weight',
    fieldName: 'Weight',
    width: 60,
    styleName: 'right-column rg-disable-cell',
    editable: false,
    header: {
      text: '중량',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0.##',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0.##',
    },
    numberFormat: '#,##0.##',
  },
  {
    name: 'Su',
    fieldName: 'Su',
    width: 60,
    styleName: 'right-column rg-disable-cell',
    editable: false,
    header: {
      text: '길이',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0.##',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0.##',
    },
    numberFormat: '#,##0.##',
  },
  {
    name: 'NapQty',
    fieldName: 'NapQty',
    width: 60,
    styleName: 'right-column rg-disable-cell',
    editable: false,
    header: {
      text: '납품량',
      showTooltip: true,
    },
    // editor: {
    //   type: 'number',
    //   editFormat: '#,##0.##',
    // },
    numberFormat: '#,##0.##',
  },
  {
    name: 'Price',
    fieldName: 'Price',
    width: 70,
    styleName: 'right-column',
    editable: true,
    header: {
      text: '단가',
      showTooltip: true,
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    renderer: {
      showTooltip: true,
    },
    numberFormat: '#,##0',
  },
  {
    name: 'Amount',
    fieldName: 'Amount',
    width: 80,
    styleName: 'right-column',
    editable: true,
    header: {
      text: '공급가액',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0.##',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0.##',
  },
  {
    name: 'Tax',
    fieldName: 'Tax',
    width: 80,
    styleName: 'right-column',
    editable: true,
    header: {
      text: '부가세',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0.##',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0.##',
  },
  {
    name: 'Okamt',
    fieldName: 'Okamt',
    width: 80,
    styleName: 'right-column',
    editable: true,
    header: {
      text: '합계금액',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0',
  },
  {
    name: 'NapDate',
    fieldName: 'NapDate',
    width: 100,
    styleName: 'center-column',
    yearNavigation: true,
    editable: true,
    header: {
      text: '납기일',
    },
    renderer: {
      type: 'text',
      showTooltip: false,
    },
    editor: {
      type: 'date',
      maxLength: 10,
      yearNavigation: true,
      datetimeFormat: 'yyyy-MM-dd',
    },
    datetimeFormat: 'yyyy-MM-dd',
  },
  {
    name: 'Remark',
    fieldName: 'Remark',
    width: 300,
    styleName: 'left-column',
    placeHolder: '최대60자',
    editable: true,
    editor: {
      maxLength: 60,
    },
    header: {
      text: '비 고',
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  // {
  //   name: 'Priceunit',
  //   fieldName: 'Priceunit',
  //   width: 60,
  //   styleName: 'left-column',
  //   button: 'action',
  //   editable: true,
  //   header: {
  //     text: '(단가단위)',
  //     showTooltip: true,
  //   },
  // },
  // {
  //   name: 'Kgperm',
  //   fieldName: 'Kgperm',
  //   width: 60,
  //   styleName: 'left-column',
  //   button: 'action',
  //   editable: true,
  //   header: {
  //     text: '(Kgperm)',
  //     showTooltip: true,
  //   },
  // },
  // {
  //   name: 'Stockunit',
  //   fieldName: 'Stockunit',
  //   width: 60,
  //   styleName: 'left-column',
  //   button: 'action',
  //   editable: true,
  //   header: {
  //     text: '(Stockunit)',
  //     showTooltip: true,
  //   },
  // },
];
