import { ValueType } from 'realgrid';

export const GridFields1 = [
  { fieldName: 'Accunit', dataType: ValueType.TEXT },
  { fieldName: 'Factory', dataType: ValueType.TEXT },
  { fieldName: 'ExportYn', dataType: ValueType.TEXT },
  { fieldName: 'DelvNo', dataType: ValueType.TEXT },
  { fieldName: 'DelvDate', dataType: ValueType.DATE, datetimeFormat: 'yyyyMMdd' },
  { fieldName: 'CustCd', dataType: ValueType.TEXT },
  { fieldName: 'Exchang', dataType: ValueType.NUMBER },
  { fieldName: 'state', dataType: ValueType.TEXT },
  { fieldName: 'Billdate', dataType: ValueType.DATE, datetimeFormat: 'yyyyMMdd' },
  { fieldName: 'TotalPrice', dataType: ValueType.NUMBER },
  { fieldName: 'TotalVat', dataType: ValueType.NUMBER },
  { fieldName: 'TotalAmount', dataType: ValueType.NUMBER },
  { fieldName: 'Qty', dataType: ValueType.NUMBER },
  { fieldName: 'ProjectNo', dataType: ValueType.TEXT },
  { fieldName: 'ActNo', dataType: ValueType.TEXT },
  { fieldName: 'CustCdNm', dataType: ValueType.TEXT },
  { fieldName: 'CustNm', dataType: ValueType.TEXT },
  { fieldName: 'Truncnm', dataType: ValueType.TEXT },
  { fieldName: 'VatNm', dataType: ValueType.TEXT },
  { fieldName: 'ProjectCustCd', dataType: ValueType.TEXT },
  { fieldName: 'ProjectCustNm', dataType: ValueType.TEXT },
  { fieldName: 'Slpdat', dataType: ValueType.TEXT },
  { fieldName: 'DocSource', dataType: ValueType.TEXT },
  { fieldName: 'Pno', dataType: ValueType.TEXT },
  { fieldName: 'DocNo', dataType: ValueType.TEXT },
  { fieldName: 'ApprDocProg', dataType: ValueType.TEXT },
  //
  { fieldName: 'Gendate', dataType: ValueType.DATE, datetimeFormat: 'yyyyMMdd' },
  { fieldName: 'DeptCD', dataType: ValueType.TEXT },
  { fieldName: 'CurrCd', dataType: ValueType.TEXT },
  { fieldName: 'Remark', dataType: ValueType.TEXT },
  { fieldName: 'TaxDate', dataType: ValueType.DATE, datetimeFormat: 'yyyyMMdd' },
  { fieldName: 'Vatcd', dataType: ValueType.TEXT },
  { fieldName: 'Sliptyp', dataType: ValueType.TEXT },
  { fieldName: 'slipno', dataType: ValueType.TEXT },
  { fieldName: 'LNKCOD', dataType: ValueType.TEXT },
  { fieldName: 'TotalForeign', dataType: ValueType.NUMBER },
  { fieldName: 'Currdate', dataType: ValueType.DATE, datetimeFormat: 'yyyyMMdd' },
  { fieldName: 'TotalAmt', dataType: ValueType.NUMBER },
  { fieldName: 'Totalweight', dataType: ValueType.NUMBER },
  { fieldName: 'UnitPrice', dataType: ValueType.NUMBER },
  { fieldName: 'UnitPricew', dataType: ValueType.NUMBER },
  { fieldName: 'PnoNm', dataType: ValueType.TEXT },
  { fieldName: 'DeptCDNm', dataType: ValueType.TEXT },
  { fieldName: 'CurrCdNm', dataType: ValueType.TEXT },
  { fieldName: 'Taxno', dataType: ValueType.TEXT },
  { fieldName: 'BL_No', dataType: ValueType.TEXT },
  { fieldName: 'DocStatus', dataType: ValueType.TEXT },
  { fieldName: 'Gubun', dataType: ValueType.TEXT },
];

export const GridColumns1 = [
  {
    name: 'ApprDocProg',
    fieldName: 'ApprDocProg',
    type: 'data',
    width: 60,
    header: {
      text: '결재상태',
    },
    styleName: 'center-column',
  },
  {
    name: 'DelvDate',
    fieldName: 'DelvDate',
    type: 'data',
    width: 80,
    header: {
      text: '입고일',
    },
    styleName: 'center-column',
    datetimeFormat: 'yyyy-MM-dd',
  },
  {
    name: 'DelvNo',
    fieldName: 'DelvNo',
    type: 'data',
    width: 95,
    header: {
      text: '입고번호',
    },
    styleName: 'center-column',
  },
  {
    name: 'CustCdNm',
    fieldName: 'CustCdNm',
    type: 'data',
    width: 100,
    header: {
      text: '거래처명',
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    styleName: 'left-column',
  },
  {
    name: 'VatNm',
    fieldName: 'VatNm',
    type: 'data',
    width: 150,
    header: {
      text: '과세종류',
    },
    styleName: 'left-column',
  },
  {
    name: 'Totalprice',
    fieldName: 'Totalprice',
    type: 'data',
    width: 80,
    header: {
      text: '공급가액',
    },
    numberFormat: '#,##0',
    styleName: 'right-column',
  },
  {
    name: 'TotalAmount',
    fieldName: 'TotalAmount',
    type: 'data',
    width: 80,
    header: {
      text: '입고총액',
    },
    numberFormat: '#,##0',
    styleName: 'right-column',
  },
  {
    name: 'Qty',
    fieldName: 'Qty',
    type: 'data',
    width: 60,
    header: {
      text: '입고량',
    },
    numberFormat: '#,##0',
    styleName: 'right-column',
  },
  {
    name: 'state',
    fieldName: 'state',
    type: 'data',
    width: 80,
    header: {
      text: '구매상태',
    },
    styleName: 'center-column',
  },
  {
    name: 'Truncnm',
    fieldName: 'Truncnm',
    type: 'data',
    width: 90,
    header: {
      text: '줄임상호',
    },
    styleName: 'left-column',
  },
];

export const GridFields2 = [
  { fieldName: 'Accunit', dataType: ValueType.TEXT },
  { fieldName: 'Guid', dataType: ValueType.TEXT },
  { fieldName: 'ExportYn', dataType: ValueType.TEXT },
  { fieldName: 'DelvNo', dataType: ValueType.TEXT },
  { fieldName: 'DelvSeq', dataType: ValueType.TEXT },
  { fieldName: 'GoodCD', dataType: ValueType.TEXT },
  { fieldName: 'Div', dataType: ValueType.TEXT },
  { fieldName: 'Spec', dataType: ValueType.TEXT },
  { fieldName: 'UnitCD', dataType: ValueType.TEXT },
  { fieldName: 'Price', dataType: ValueType.NUMBER },
  // { fieldName: 'PriceTaxYn', dataType: ValueType.TEXT },
  { fieldName: 'Delvqty', dataType: ValueType.NUMBER },
  { fieldName: 'Weight', dataType: ValueType.NUMBER },
  { fieldName: 'Su', dataType: ValueType.NUMBER },
  { fieldName: 'Qty', dataType: ValueType.NUMBER },
  { fieldName: 'InQty', dataType: ValueType.NUMBER },
  { fieldName: 'Amount', dataType: ValueType.NUMBER },
  { fieldName: 'KorAmt', dataType: ValueType.NUMBER },
  { fieldName: 'StockYn', dataType: ValueType.TEXT },
  { fieldName: 'StockQty', dataType: ValueType.NUMBER },
  // { fieldName: 'QcYn', dataType: ValueType.TEXT },
  // { fieldName: 'QcPno', dataType: ValueType.TEXT },
  // { fieldName: 'QcDate', dataType: ValueType.TEXT },
  // { fieldName: 'QcQty', dataType: ValueType.TEXT },
  // { fieldName: 'QcAmt', dataType: ValueType.TEXT },
  // { fieldName: 'OkQty', dataType: ValueType.TEXT },
  { fieldName: 'OkAmt', dataType: ValueType.NUMBER },
  // { fieldName: 'OkKorAmt', dataType: ValueType.TEXT },
  // { fieldName: 'OkStdUnitQty', dataType: ValueType.TEXT },
  { fieldName: 'Tax', dataType: ValueType.NUMBER },
  { fieldName: 'Whcd', dataType: ValueType.TEXT },
  // { fieldName: 'SttLitem', dataType: ValueType.TEXT },
  // { fieldName: 'WhCheckYn', dataType: ValueType.TEXT },
  { fieldName: 'No', dataType: ValueType.TEXT },
  // { fieldName: 'Pono', dataType: ValueType.TEXT },
  // { fieldName: 'PoSerl', dataType: ValueType.TEXT },
  // { fieldName: 'LcNo', dataType: ValueType.TEXT },
  // { fieldName: 'LcSeq', dataType: ValueType.TEXT },
  { fieldName: 'BalNo', dataType: ValueType.TEXT },
  { fieldName: 'BalSerl', dataType: ValueType.TEXT },
  { fieldName: 'Sourcetype', dataType: ValueType.TEXT },
  // { fieldName: 'CntlNo', dataType: ValueType.TEXT },
  // { fieldName: 'CntlSeq', dataType: ValueType.TEXT },
  // { fieldName: 'Lotno', dataType: ValueType.TEXT },
  // { fieldName: 'ToSerl', dataType: ValueType.TEXT },
  // { fieldName: 'FormSerl', dataType: ValueType.TEXT },
  // { fieldName: 'CrePno', dataType: ValueType.TEXT },
  // { fieldName: 'CreDate', dataType: ValueType.TEXT },
  // { fieldName: 'ModPno', dataType: ValueType.TEXT },
  // { fieldName: 'ModDate', dataType: ValueType.TEXT },
  { fieldName: 'NapQty', dataType: ValueType.NUMBER },
  // { fieldName: 'BalQty', dataType: ValueType.TEXT },
  { fieldName: 'GoodNo', dataType: ValueType.TEXT },
  { fieldName: 'GoodCdNm', dataType: ValueType.TEXT },
  { fieldName: 'color', dataType: ValueType.TEXT },
  { fieldName: 'goodenm', dataType: ValueType.TEXT },
  { fieldName: 'UnitCdNm', dataType: ValueType.TEXT },
  { fieldName: 'WhCdNm', dataType: ValueType.TEXT },
  // { fieldName: 'TrackingNo', dataType: ValueType.TEXT },
  // { fieldName: 'OrderNo', dataType: ValueType.TEXT },
  // { fieldName: 'Ci_No', dataType: ValueType.TEXT },
  { fieldName: 'jukyocd', dataType: ValueType.TEXT },
  { fieldName: 'jukyonm', dataType: ValueType.TEXT },
  { fieldName: 'GFactory', dataType: ValueType.TEXT },
  { fieldName: 'Factory', dataType: ValueType.TEXT },
  { fieldName: 'goodtype', dataType: ValueType.TEXT },
  { fieldName: 'GWeight', dataType: ValueType.NUMBER },
  { fieldName: 'KgPerM', dataType: ValueType.NUMBER },
  { fieldName: 'Priceunit', dataType: ValueType.TEXT },
  { fieldName: 'Priceunitnm', dataType: ValueType.TEXT },
  // { fieldName: 'TwistUnit', dataType: ValueType.TEXT },
  // { fieldName: 'TwistUnitNm', dataType: ValueType.TEXT },
  { fieldName: 'BoxUnit', dataType: ValueType.TEXT },
  { fieldName: 'BoxUnitNm', dataType: ValueType.TEXT },
  // { fieldName: 'Carno', dataType: ValueType.TEXT },
  // { fieldName: 'Carnonm', dataType: ValueType.TEXT },
  { fieldName: 'Actno', dataType: ValueType.TEXT },
  { fieldName: 'Actgoodcd', dataType: ValueType.TEXT },
  { fieldName: 'Actgoodno', dataType: ValueType.TEXT },
  { fieldName: 'Unitweight', dataType: ValueType.NUMBER },
  { fieldName: 'ForeignAmt', dataType: ValueType.NUMBER },
  { fieldName: 'Remark', dataType: ValueType.TEXT },
  { fieldName: 'Bomchecksort', dataType: ValueType.TEXT },
];

export const GridColumns2 = [
  {
    name: 'No',
    fieldName: 'No',
    width: 50,
    styleName: 'center-column',
    editable: false,
    header: {
      text: 'NO',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'GoodNo',
    fieldName: 'GoodNo',
    width: 170,
    styleName: 'left-column',
    header: {
      text: '품번',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    editor: {
      textCase: 'upper',
    },
  },
  {
    name: 'Spec',
    fieldName: 'Spec',
    width: 140,
    styleName: 'left-column',
    // editable: false,
    header: {
      text: '규격',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    editor: {
      maxLength: 25,
    },
  },
  {
    name: 'GoodCdNm',
    fieldName: 'GoodCdNm',
    width: 150,
    styleName: 'left-column',
    // editable: false,
    button: 'action',
    header: {
      text: '품명',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },

  {
    name: 'Delvqty',
    fieldName: 'Delvqty',
    width: 50,
    styleName: 'right-column rg-disable-cell',
    editable: false,
    header: {
      text: '구매량',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0.##',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0.##',
    },
    numberFormat: '#,##0.##',
  },
  {
    name: 'Su',
    fieldName: 'Su',
    width: 50,
    styleName: 'right-column',
    editable: false,
    header: {
      text: '길이',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0',
  },
  {
    name: 'Qty',
    fieldName: 'Qty',
    width: 50,
    styleName: 'right-column',
    header: {
      text: '수량',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0',
  },
  {
    name: 'Unitweight',
    fieldName: 'Unitweight',
    width: 60,
    styleName: 'right-column',
    header: {
      text: '단위중량',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    editor: {
      type: 'number',
      editFormat: '#,##0.##',
    },
    numberFormat: '#,##0.##',
  },
  {
    name: 'Weight',
    fieldName: 'Weight',
    width: 50,
    styleName: 'right-column rg-disable-cell',
    editable: false,
    header: {
      text: '중량',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    editor: {
      type: 'number',
      editFormat: '#,##0.##',
    },
    footer: {
      numberFormat: '#,##0.##',
      expression: 'sum',
    },
    numberFormat: '#,##0.##',
  },
  {
    name: 'Priceunitnm',
    fieldName: 'Priceunitnm',
    width: 80,
    styleName: 'center-column',
    button: 'action',
    header: {
      text: '단가단위',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'Price',
    fieldName: 'Price',
    width: 70,
    styleName: 'right-column',
    header: {
      text: '단가',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0',
  },
  {
    name: 'Amount',
    fieldName: 'Amount',
    width: 80,
    styleName: 'right-column',
    header: {
      text: '공급가액',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0',
  },
  {
    name: 'Tax',
    fieldName: 'Tax',
    width: 70,
    styleName: 'right-column',
    header: {
      text: '부가세',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0',
      expression: 'sum',
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0',
  },
  {
    name: 'OkAmt',
    fieldName: 'OkAmt',
    width: 80,
    styleName: 'right-column rg-disable-cell',
    editable: false,
    header: {
      text: '합계금액',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0',
  },
  {
    name: 'ForeignAmt',
    fieldName: 'ForeignAmt',
    width: 80,
    styleName: 'right-column',
    header: {
      text: '외화합계금액',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    footer: {
      numberFormat: '#,##0',
      expression: 'sum',
    },
    editor: {
      type: 'number',
      editFormat: '#,##0',
    },
    numberFormat: '#,##0',
  },
  {
    name: 'jukyocd',
    fieldName: 'jukyocd',
    width: 80,
    styleName: 'center-column right-column rg-disable-cell',
    editable: false,
    header: {
      text: '회계처리코드',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'jukyonm',
    fieldName: 'jukyonm',
    width: 90,
    styleName: 'left-column',
    button: 'action',
    header: {
      text: '회계처리코드명',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'WhCdNm',
    fieldName: 'WhCdNm',
    width: 80,
    styleName: 'left-column',
    button: 'action',
    header: {
      text: '입고창고',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'StockYn',
    fieldName: 'StockYn',
    type: 'data',
    width: 40,
    header: {
      text: '재고',
    },
    renderer: {
      type: 'check',
      trueValues: 'Y',
      falseValues: 'N',
    },
  },
  {
    name: 'Remark',
    fieldName: 'Remark',
    width: 250,
    styleName: 'left-column',
    placeHolder: '최대100자',
    header: {
      text: '비고',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
    editor: {
      maxLength: 100,
    },
  },
  {
    name: 'Actgoodcd',
    fieldName: 'Actgoodcd',
    width: 100,
    styleName: 'left-column, rg-disable-cell',
    editable: false,
    header: {
      text: '수주품번',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'ActNo',
    fieldName: 'ActNo',
    width: 80,
    styleName: 'left-column, rg-disable-cell',
    editable: false,
    header: {
      text: '수결번호',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
  {
    name: 'Bomchecksort',
    fieldName: 'Bomchecksort',
    width: 100,
    styleName: 'left-column, rg-disable-cell',
    editable: false,
    header: {
      text: 'Bomchecksort',
      showTooltip: true,
    },
    renderer: {
      type: 'text',
      showTooltip: true,
    },
  },
];
